### ISSUE TITLE
你好，我想问一下为什么在执行删除操作的时候，他删不了，后端报这样的错。好像是那个查询条件id的问题。

### ISSUE THREAD

**Issue by MrAYu** [liutengjian66/COVID#2]
因为我看到你那里的id后面总是加了一个id+”L“

错误是这样的：
[Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: 
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DOUBLE value: '13L'
; Data truncation: Truncated incorrect DOUBLE value: '13L'; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DOUBLE value: '13L'] with root cause

com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DOUBLE value: '13L'

**Comment by Edgar1115** [comment]
请问解决了吗？

**Comment by MrAYu** [comment]
您好，没有解决。就是删除报错。我感觉是因为删除的条件（id）在传入后端到数据库的时候，可能id没有被识别。因为我看后端的id都是数字，但是传过去就是一个数字后面加了一个L

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月2日(周一) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liutengjian66/COVID] 你好，我想问一下为什么在执行删除操作的时候，他删不了，后端报这样的错。好像是那个查询条件id的问题。 (Issue #2)




 
请问解决了吗？

**Comment by Edgar1115** [comment]
> 

你好，我试了一下，把“L”删除掉就可以正常进行删除操作了

**Comment by MrAYu** [comment]
好的，我试一下。麻烦您了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月2日(周一) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liutengjian66/COVID] 你好，我想问一下为什么在执行删除操作的时候，他删不了，后端报这样的错。好像是那个查询条件id的问题。 (Issue #2)




   
你好，我试了一下，把“L”删除掉就可以正常进行删除操作了

**Comment by tengJL66** [comment]
应该是当时多加了个‘L’，源码应该后面上传的时候被我瞎改动了，多此一举了，忘改回去。抱歉，还不怎么会用github。
`
@DeleteMapping("/deleteById/{id}")
    public void deleteById(@PathVariable("id")Long id){
        mapper.deleteById(id);
    }
`

**Comment by zzzjun13** [comment]
你好，这个登录不进去啊
